# Stat 340: Introduction to Data Modeling II (aka World, Data, and Models)
### Spring 2021
## UW-Madison
### Karl Rohe
email: first name and last name at stat dott wisc dott edu  
office: 1239 MSC  
[Syllabus](syllabus.pdf), [text](text/worldDataModels.html),   [R labs](labs.R), and [Project description](projectDescription.html).



### Week 1  
#### Topics 
1) This is a fun and important course because...      
- This is not an intro course.  This course serves as a gateway to the advanced courses.  
- This is not a math course.  This is a statistics course.  More specifically, it is an applied statistics course. 
- Why should we study statistics?
2) [Go over syllabus](syllabus.pdf)
3) Introductions to course aims and texts. [World, Data, Models](text/worldDataModels.html)


#### Lecture discussion questions
1) What is your major?  
1) Why are you in this class?
3) What type of thing are you interested in studying?  Topics? Do you think you could find data that you would find interesting?


#### Homework 

- [homework1](01-GenerateRandomVariables.html)
-  Form groups of three. Within your group, you should have similar interests (i.e. project topics). Talk to your friends or look for group members in discussion section. Next Thursday, sit with your group. On Thursday, if you have not found a group, that is totally fine! We will have a *free agent* session in class.
- Next week, we will have a reading quiz on [this article](https://hbr.org/2016/10/noise).  As you are reading, consider how this article might be related to our course.


#### Texts: 
[*An Introduction to Statistical Learning with Applications in R*](http://www-bcf.usc.edu/~gareth/ISL/)  
by Gareth James, Daniela Witten, Trevor Hastie and Robert Tibshirani  

For reference:  [*R for Data Science*](http://r4ds.had.co.nz) by Garrett Grolemund and Hadley Wickham


#### Helpful links
1) [Download ISLR text](http://www-bcf.usc.edu/~gareth/ISL/) and lab codes.   
4) Making beautiful documents with [R markdown](http://rmarkdown.rstudio.com).  [some](../ht/rmarkdown-cheatsheet.pdf) helpful [links](../ht/rmarkdown-reference.pdf).

#### Will we get to these topics?  
1) [Nonlinear regression; splines, lowess, generalized additive models](../ht/07-nonlinear.pdf)  
2) [Random Forests and tree based methods](../ht/08-trees.pdf)  
3) [k-means](../ht/10-unsupervised.pdf)  
